# Site settings
title: Alex Kompos
description: muh landing page
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alex Kompos
user_description: Just a guy doing his best to level up his Dev skills and also my much beloved Ops skills. Will these come together and conlminate in the buzzword which invouge at the moment (DevOps)?....probably.
user_title: (Dev) + (Ops)
email: alexkompos@gmail.com
twitter_username: a_kompos
github_username:  stackapack
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
